export const queryKeys = {
    activities: (rootId) => ['activities', rootId],
    activeProgramDays: (rootId) => ['active-program-days', rootId],
    analyticsSessions: (rootId, limit = 50) => ['analytics-sessions', rootId, limit],
    activityHistory: (rootId, activityDefinitionId, excludeSessionId = null, limit = 10) => [
        'activity-history',
        rootId,
        activityDefinitionId,
        excludeSessionId,
        limit,
    ],
    activityGroups: (rootId) => ['activity-groups', rootId],
    activityModes: (rootId) => ['activity-modes', rootId],
    annotations: (rootId, visualizationType, contextKey = '{}') => [
        'annotations',
        rootId,
        visualizationType,
        contextKey,
    ],
    fractalTree: (rootId) => ['fractalTree', rootId],
    fractals: () => ['fractals'],
    goalActivities: (rootId, goalId) => ['goalActivities', rootId, goalId],
    goalActivityGroups: (rootId, goalId) => ['goalActivityGroups', rootId, goalId],
    goalLevels: (rootId) => ['goalLevels', rootId],
    goalDailyDurations: (goalId) => ['goalDailyDurations', goalId],
    goalAnalytics: (rootId) => ['goal-analytics', rootId],
    goalMetrics: (goalId) => ['goalMetrics', goalId],
    goals: (rootId) => ['goals', rootId],
    goalsForSelection: (rootId) => ['goalsForSelection', rootId],
    goalsTree: (rootId) => ['goals-tree', rootId],
    logs: (rootId, page = 1, pageSize = 50, eventType = 'all', startDate = '', endDate = '') => [
        'logs',
        rootId,
        page,
        pageSize,
        eventType,
        startDate,
        endDate,
    ],
    program: (rootId, programId) => ['program', rootId, programId],
    programs: (rootId) => ['programs', rootId],
    session: (rootId, sessionId) => ['session', rootId, sessionId],
    sessionActivities: (rootId, sessionId) => ['session-activities', rootId, sessionId],
    sessionGoalsView: (rootId, sessionId) => ['session-goals-view', rootId, sessionId],
    sessionMicroGoals: (rootId) => ['session-micro-goals', rootId],
    sessionNotes: (rootId, sessionId) => ['session-notes', rootId, sessionId],
    sessionTemplates: (rootId) => ['session-templates', rootId],
    previousSessionNotes: (rootId, sessionId) => ['previous-session-notes', rootId, sessionId],
    activityDefinitionNotes: (rootId, activityDefinitionId) => ['activity-definition-notes', rootId, activityDefinitionId],
    sessions: (rootId) => ['sessions', rootId],
    sessionsAll: (rootId) => ['sessions', rootId, 'all'],
    sessionsSearch: (rootId, filters = {}) => ['sessions', rootId, 'search', filters],
    sessionsHeatmap: (rootId, filters = {}) => ['sessions', rootId, 'heatmap', filters],
    sessionsPaginated: (rootId) => ['sessions', rootId, 'paginated'],
};
