export const queryKeys = {
    activities: (rootId) => ['activities', rootId],
    activeProgramDays: (rootId) => ['active-program-days', rootId],
    analyticsSummary: (rootId, limit = 50) => ['analytics-summary', rootId, limit],
    analyticsSessions: (rootId, limit = 50) => ['analytics-sessions', rootId, limit],
    activityHistory: (rootId, activityDefinitionId, excludeSessionId = null, limit = 10) => [
        'activity-history',
        rootId,
        activityDefinitionId,
        excludeSessionId,
        limit,
    ],
    activityHistoryRoot: (rootId) => ['activity-history', rootId],
    activityInstantiationSummary: (rootId) => ['activity-instantiation-summary', rootId],
    activityGroups: (rootId) => ['activity-groups', rootId],
    fractalMetrics: (rootId) => ['fractal-metrics', rootId],
    analyticsViews: (rootId) => ['analytics-views', rootId],
    analyticsCatalog: () => ['analytics-engine', 'catalog'],
    analyticsQueryProfiles: () => ['analytics-engine', 'query-profiles'],
    analyticsQueryRun: (querySpec) => ['analytics-engine', 'query-run', querySpec],
    dashboards: (rootId) => ['analytics-views', rootId],
    rootGoal: (rootId) => ['root-goal', rootId],
    fractalTree: (rootId) => ['fractalTree', rootId],
    fractals: (userId = null) => userId ? ['fractals', userId] : ['fractals'],
    goalActivities: (rootId, goalId) => ['goalActivities', rootId, goalId],
    goalActivitiesRoot: (rootId) => ['goalActivities', rootId],
    goalActivityGroups: (rootId, goalId) => ['goalActivityGroups', rootId, goalId],
    goalActivityGroupsRoot: (rootId) => ['goalActivityGroups', rootId],
    goalLevels: (rootId, userId = null) => userId ? ['goalLevels', rootId, userId] : ['goalLevels', rootId],
    goalDailyDurations: (goalId) => ['goalDailyDurations', goalId],
    goalTimeline: (rootId, goalId, types = [], includeChildren = true, limit = 50) => [
        'goalTimeline',
        rootId,
        goalId,
        [...types].sort(),
        includeChildren,
        limit,
    ],
    goalTimelineRoot: (rootId, goalId) => ['goalTimeline', rootId, goalId],
    goalAnalytics: (rootId) => ['goal-analytics', rootId],
    targetAnalytics: (rootId, targetId, since = 'creation') => ['targetAnalytics', rootId, targetId, since],
    targetAnalyticsRoot: (rootId, targetId) => ['targetAnalytics', rootId, targetId],
    goalActivityInstances: (rootId, goalId, activityId) => ['goalActivityInstances', rootId, goalId, activityId],
    goalActivityInstancesRoot: (rootId, goalId) => ['goalActivityInstances', rootId, goalId],
    goalMetrics: (goalId) => ['goalMetrics', goalId],
    goalMetricsRoot: () => ['goalMetrics'],
    eligibleMoveParents: (rootId, goalId) => ['goals', rootId, 'eligibleMoveParents', goalId],
    goals: (rootId) => ['goals', rootId],
    goalsForSelection: (rootId) => ['goalsForSelection', rootId],
    goalsTree: (rootId) => ['goals-tree', rootId],
    logs: (rootId, page = 1, pageSize = 50, eventType = 'all', startDate = '', endDate = '') => [
        'logs',
        rootId,
        page,
        pageSize,
        eventType,
        startDate,
        endDate,
    ],
    landingExamples: () => ['public', 'landing-examples'],
    logsInfinite: (rootId, pageSize = 50) => ['logs', rootId, 'infinite', pageSize],
    logsInfiniteRoot: (rootId) => ['logs', rootId, 'infinite'],
    program: (rootId, programId) => ['program', rootId, programId],
    programs: (rootId) => ['programs', rootId],
    session: (rootId, sessionId) => ['session', rootId, sessionId],
    sessionRoot: (rootId) => ['session', rootId],
    sessionActivities: (rootId, sessionId) => ['session-activities', rootId, sessionId],
    sessionActivitiesRoot: (rootId) => ['session-activities', rootId],
    sessionGoalsView: (rootId, sessionId) => ['session-goals-view', rootId, sessionId],
    sessionGoalsViewRoot: (rootId) => ['session-goals-view', rootId],
    sessionNotes: (rootId, sessionId) => ['session-notes', rootId, sessionId],
    sessionNotesRoot: (rootId) => ['session-notes', rootId],
    sessionTemplates: (rootId) => ['session-templates', rootId],
    previousSessionNotes: (rootId, sessionId) => ['previous-session-notes', rootId, sessionId],
    activityDefinitionNotes: (rootId, activityDefinitionId) => ['activity-definition-notes', rootId, activityDefinitionId],
    sessions: (rootId) => ['sessions', rootId],
    sessionsAll: (rootId) => ['sessions', rootId, 'all'],
    sessionsEvidenceGoalsRoot: (rootId) => ['sessions', rootId, 'evidence-goals'],
    sessionsEvidenceGoals: (rootId, days) => ['sessions', rootId, 'evidence-goals', days],
    sessionsFlowtreeMetricsRoot: (rootId) => ['sessions', rootId, 'flowtree-metrics'],
    sessionsFlowtreeMetrics: (rootId, goalIds = [], days) => ['sessions', rootId, 'flowtree-metrics', goalIds, days],
    sessionsSearch: (rootId, filters = {}) => ['sessions', rootId, 'search', filters],
    sessionsHeatmap: (rootId, filters = {}) => ['sessions', rootId, 'heatmap', filters],
    sessionsPaginated: (rootId) => ['sessions', rootId, 'paginated'],
    goalNotes: (rootId, goalId, includeDescendants = false) => ['goal-notes', rootId, goalId, includeDescendants],
    goalNotesRoot: (rootId) => ['goal-notes', rootId],
    allNotes: (rootId, filters = {}) => ['all-notes', rootId, filters],
    allNotesRoot: (rootId) => ['all-notes', rootId],
    progressRoot: () => ['progress'],
    progressComparison: (instanceId) => ['progress', 'comparison', instanceId],
    progressHistory: (activityDefId, excludeSessionId = null) => ['progress', 'history', activityDefId, excludeSessionId],
    progressHistoryRoot: (activityDefId) => ['progress', 'history', activityDefId],
    sessionProgressSummary: (sessionId) => ['progress', 'session', sessionId],
};
