export const queryKeys = {
    activities: (rootId) => ['activities', rootId],
    activityHistory: (rootId, activityDefinitionId, excludeSessionId = null, limit = 10) => [
        'activity-history',
        rootId,
        activityDefinitionId,
        excludeSessionId,
        limit,
    ],
    activityGroups: (rootId) => ['activity-groups', rootId],
    annotations: (rootId, visualizationType, contextKey = '{}') => [
        'annotations',
        rootId,
        visualizationType,
        contextKey,
    ],
    fractalTree: (rootId) => ['fractalTree', rootId],
    fractals: () => ['fractals'],
    goalActivities: (rootId, goalId) => ['goalActivities', rootId, goalId],
    goalActivityGroups: (rootId, goalId) => ['goalActivityGroups', rootId, goalId],
    goalLevels: (rootId) => ['goalLevels', rootId],
    goalDailyDurations: (goalId) => ['goalDailyDurations', goalId],
    goalMetrics: (goalId) => ['goalMetrics', goalId],
    goals: (rootId) => ['goals', rootId],
    goalsForSelection: (rootId) => ['goalsForSelection', rootId],
    goalsTree: (rootId) => ['goals-tree', rootId],
    program: (rootId, programId) => ['program', rootId, programId],
    programs: (rootId) => ['programs', rootId],
    session: (rootId, sessionId) => ['session', rootId, sessionId],
    sessionActivities: (rootId, sessionId) => ['session-activities', rootId, sessionId],
    sessionGoalsView: (rootId, sessionId) => ['session-goals-view', rootId, sessionId],
    sessionMicroGoals: (rootId) => ['session-micro-goals', rootId],
    sessionNotes: (rootId, sessionId) => ['session-notes', rootId, sessionId],
    previousSessionNotes: (rootId, sessionId) => ['previous-session-notes', rootId, sessionId],
    activityDefinitionNotes: (rootId, activityDefinitionId) => ['activity-definition-notes', rootId, activityDefinitionId],
    sessions: (rootId) => ['sessions', rootId],
    sessionsAll: (rootId) => ['sessions', rootId, 'all'],
    sessionsPaginated: (rootId) => ['sessions', rootId, 'paginated'],
};
