import { API_BASE, axios } from './core';

export const adminApi = {
    getSummary: () => axios.get(`${API_BASE}/admin/summary`),
    getUsers: (params = {}) => axios.get(`${API_BASE}/admin/users`, { params }),
    getTierQuotas: () => axios.get(`${API_BASE}/admin/tier-quotas`),
    updateTierQuotas: (data) => axios.patch(`${API_BASE}/admin/tier-quotas`, data),
    getFeatureFlags: () => axios.get(`${API_BASE}/admin/feature-flags`),
    updateFeatureFlags: (data) => axios.patch(`${API_BASE}/admin/feature-flags`, data),
    getLandingExamples: () => axios.get(`${API_BASE}/admin/landing-examples`),
    getLandingExampleOptions: (rootId) => axios.get(`${API_BASE}/admin/landing-examples/options`, { params: { root_id: rootId } }),
    updateLandingExamples: (data) => axios.patch(`${API_BASE}/admin/landing-examples`, data),
    publishLandingExamples: (data = {}) => axios.post(
        `${API_BASE}/admin/landing-examples/publish`,
        data,
        { timeout: 90000 }
    ),
    createUser: (data) => axios.post(`${API_BASE}/admin/users`, data),
    updateUser: (userId, data) => axios.patch(`${API_BASE}/admin/users/${userId}`, data),
    softDeleteUser: (userId) => axios.delete(`${API_BASE}/admin/users/${userId}/soft-delete`),
    hardDeleteUser: (userId) => axios.delete(`${API_BASE}/admin/users/${userId}/hard-delete`),
    generateTemporaryPassword: (userId) => axios.post(`${API_BASE}/admin/users/${userId}/temporary-password`),
    updateUserTier: (userId, data) => axios.patch(`${API_BASE}/admin/users/${userId}/tier`, data),
    updateUserQuota: (userId, data) => axios.patch(`${API_BASE}/admin/users/${userId}/quota`, data),
    updateUserStatus: (userId, data) => axios.patch(`${API_BASE}/admin/users/${userId}/status`, data),
    unlockUser: (userId) => axios.patch(`${API_BASE}/admin/users/${userId}/unlock`),
    forcePasswordChange: (userId, data = { force_password_change: true }) => axios.patch(`${API_BASE}/admin/users/${userId}/force-password-change`, data),
    updateUserRole: (userId, data) => axios.patch(`${API_BASE}/admin/users/${userId}/role`, data),
    getInviteKeys: () => axios.get(`${API_BASE}/admin/invite-keys`),
    createInviteKey: (data) => axios.post(`${API_BASE}/admin/invite-keys`, data),
    revokeInviteKey: (inviteId) => axios.patch(`${API_BASE}/admin/invite-keys/${inviteId}/revoke`),
    getBetaSignups: (params = {}) => axios.get(`${API_BASE}/admin/beta-signups`, { params }),
    updateBetaSignupStatus: (signupId, data) => axios.patch(`${API_BASE}/admin/beta-signups/${signupId}`, data),
    sendBetaSignupInvite: (signupId) => axios.post(`${API_BASE}/admin/beta-signups/${signupId}/send-invite`, {}),
    exportBetaSignupsCsv: (params = {}) => axios.get(`${API_BASE}/admin/beta-signups/export.csv`, { params, responseType: 'blob' }),
};
