"""add pause fields

Revision ID: 504e9d2382da
Revises: 9119bd58face
Create Date: 2026-02-23 16:17:45.431250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504e9d2382da'
down_revision: Union[str, Sequence[str], None] = '9119bd58face'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_instances', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.add_column('activity_instances', sa.Column('last_paused_at', sa.DateTime(), nullable=True))
    op.add_column('activity_instances', sa.Column('total_paused_seconds', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('last_paused_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('total_paused_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'total_paused_seconds')
    op.drop_column('sessions', 'last_paused_at')
    op.drop_column('sessions', 'is_paused')
    op.drop_column('activity_instances', 'total_paused_seconds')
    op.drop_column('activity_instances', 'last_paused_at')
    op.drop_column('activity_instances', 'is_paused')
    # ### end Alembic commands ###
