"""Change ProgramBlock goal_ids to JSONB

Revision ID: 6b917fe24076
Revises: e51e92965cf8
Create Date: 2026-01-23 11:13:24.890705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b917fe24076'
down_revision: Union[str, Sequence[str], None] = 'e51e92965cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, fill existing NULLs with empty array
    op.execute("UPDATE program_blocks SET goal_ids = '[]' WHERE goal_ids IS NULL")
    
    op.alter_column('program_blocks', 'goal_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               nullable=False,
               postgresql_using='goal_ids::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program_blocks', 'goal_ids',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
