"""Add session_template_goals and program_day_goals tables

Revision ID: 7080ee18b7a9
Revises: f55ae9e336e0
Create Date: 2026-02-04 13:15:28.060152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7080ee18b7a9'
down_revision: Union[str, Sequence[str], None] = 'f55ae9e336e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_template_goals',
    sa.Column('session_template_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_template_id'], ['session_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_template_id', 'goal_id')
    )
    op.create_table('program_day_goals',
    sa.Column('program_day_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_day_id', 'goal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_day_goals')
    op.drop_table('session_template_goals')
    # ### end Alembic commands ###
