"""Add program progress tracking

Revision ID: 9119bd58face
Revises: 82825d5165d4
Create Date: 2026-02-22 20:58:39.582416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9119bd58face'
down_revision: Union[str, Sequence[str], None] = '82825d5165d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_blocks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('programs', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('programs', sa.Column('goals_completed', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('goals_total', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('completion_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'completion_percentage')
    op.drop_column('programs', 'goals_total')
    op.drop_column('programs', 'goals_completed')
    op.drop_column('programs', 'is_completed')
    op.drop_column('program_blocks', 'is_completed')
    # ### end Alembic commands ###
