"""add_missing_indexes

Revision ID: 94a9feab5041
Revises: becb5d8f061c
Create Date: 2026-02-01 13:15:32.230896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a9feab5041'
down_revision: Union[str, Sequence[str], None] = 'becb5d8f061c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_definitions_group_id'), 'activity_definitions', ['group_id'], unique=False)
    op.create_index(op.f('ix_activity_instances_activity_definition_id'), 'activity_instances', ['activity_definition_id'], unique=False)
    op.create_index(op.f('ix_metric_definitions_activity_id'), 'metric_definitions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_program_blocks_program_id'), 'program_blocks', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_days_block_id'), 'program_days', ['block_id'], unique=False)
    op.create_index(op.f('ix_split_definitions_activity_id'), 'split_definitions', ['activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_definitions_activity_id'), table_name='split_definitions')
    op.drop_index(op.f('ix_program_days_block_id'), table_name='program_days')
    op.drop_index(op.f('ix_program_blocks_program_id'), table_name='program_blocks')
    op.drop_index(op.f('ix_metric_definitions_activity_id'), table_name='metric_definitions')
    op.drop_index(op.f('ix_activity_instances_activity_definition_id'), table_name='activity_instances')
    op.drop_index(op.f('ix_activity_definitions_group_id'), table_name='activity_definitions')
    # ### end Alembic commands ###
