"""add goal level characteristics columns

Revision ID: 9f85bd56a5ec
Revises: 6cd6d0e3f98b
Create Date: 2026-02-20 14:00:14.023551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f85bd56a5ec'
down_revision: Union[str, Sequence[str], None] = '6cd6d0e3f98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_levels', sa.Column('deadline_min_days', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('deadline_max_days', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('max_children', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('auto_complete_when_children_done', sa.Boolean(), nullable=True))
    op.add_column('goal_levels', sa.Column('can_have_targets', sa.Boolean(), nullable=True))
    op.add_column('goal_levels', sa.Column('session_linkable', sa.Boolean(), nullable=True))
    op.add_column('goal_levels', sa.Column('description_required', sa.Boolean(), nullable=True))
    op.add_column('goal_levels', sa.Column('default_deadline_offset_days', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('sort_children_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_levels', 'sort_children_by')
    op.drop_column('goal_levels', 'default_deadline_offset_days')
    op.drop_column('goal_levels', 'description_required')
    op.drop_column('goal_levels', 'session_linkable')
    op.drop_column('goal_levels', 'can_have_targets')
    op.drop_column('goal_levels', 'auto_complete_when_children_done')
    op.drop_column('goal_levels', 'max_children')
    op.drop_column('goal_levels', 'deadline_max_days')
    op.drop_column('goal_levels', 'deadline_min_days')
    # ### end Alembic commands ###
