"""replace deadline days with value unit pairs

Revision ID: b60fe69a83e0
Revises: 9f85bd56a5ec
Create Date: 2026-02-20 14:15:44.012975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60fe69a83e0'
down_revision: Union[str, Sequence[str], None] = '9f85bd56a5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_levels', sa.Column('deadline_min_value', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('deadline_min_unit', sa.String(), nullable=True))
    op.add_column('goal_levels', sa.Column('deadline_max_value', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('deadline_max_unit', sa.String(), nullable=True))
    op.add_column('goal_levels', sa.Column('default_deadline_offset_value', sa.Integer(), nullable=True))
    op.add_column('goal_levels', sa.Column('default_deadline_offset_unit', sa.String(), nullable=True))
    op.drop_column('goal_levels', 'default_deadline_offset_days')
    op.drop_column('goal_levels', 'deadline_max_days')
    op.drop_column('goal_levels', 'deadline_min_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_levels', sa.Column('deadline_min_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('goal_levels', sa.Column('deadline_max_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('goal_levels', sa.Column('default_deadline_offset_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('goal_levels', 'default_deadline_offset_unit')
    op.drop_column('goal_levels', 'default_deadline_offset_value')
    op.drop_column('goal_levels', 'deadline_max_unit')
    op.drop_column('goal_levels', 'deadline_max_value')
    op.drop_column('goal_levels', 'deadline_min_unit')
    op.drop_column('goal_levels', 'deadline_min_value')
    # ### end Alembic commands ###
