"""add customization columns to goal_levels

Revision ID: bd71cb89beb8
Revises: d9137345cd3a
Create Date: 2026-02-20 10:32:58.773720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd71cb89beb8'
down_revision: Union[str, Sequence[str], None] = 'd9137345cd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_levels', sa.Column('owner_id', sa.String(), nullable=True))
    op.add_column('goal_levels', sa.Column('root_id', sa.String(), nullable=True))
    op.add_column('goal_levels', sa.Column('allow_manual_completion', sa.Boolean(), nullable=True))
    op.add_column('goal_levels', sa.Column('track_activities', sa.Boolean(), nullable=True))
    op.add_column('goal_levels', sa.Column('requires_smart', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_goal_levels_owner_id'), 'goal_levels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_goal_levels_root_id'), 'goal_levels', ['root_id'], unique=False)
    op.create_foreign_key(None, 'goal_levels', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal_levels', type_='foreignkey')
    op.drop_index(op.f('ix_goal_levels_root_id'), table_name='goal_levels')
    op.drop_index(op.f('ix_goal_levels_owner_id'), table_name='goal_levels')
    op.drop_column('goal_levels', 'requires_smart')
    op.drop_column('goal_levels', 'track_activities')
    op.drop_column('goal_levels', 'allow_manual_completion')
    op.drop_column('goal_levels', 'root_id')
    op.drop_column('goal_levels', 'owner_id')
    # ### end Alembic commands ###
