"""drop session_linkable column

Revision ID: c6535c43d656
Revises: b60fe69a83e0
Create Date: 2026-02-20 14:19:28.677132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6535c43d656'
down_revision: Union[str, Sequence[str], None] = 'b60fe69a83e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_levels', 'session_linkable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_levels', sa.Column('session_linkable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
