"""enforce_pause_constraints

Revision ID: d0e371b35146
Revises: 504e9d2382db
Create Date: 2026-02-24 19:56:28.879798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e371b35146'
down_revision: Union[str, Sequence[str], None] = '504e9d2382db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_instances', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('activity_instances', 'total_paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('sessions', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('sessions', 'total_paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'total_paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('sessions', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('activity_instances', 'total_paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('activity_instances', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
