"""add_frozen_fields_to_goals

Revision ID: d4d467d80f3c
Revises: 4ab0f1b9c2de
Create Date: 2026-03-19 14:05:05.333294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d467d80f3c'
down_revision: Union[str, Sequence[str], None] = '4ab0f1b9c2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('frozen', sa.Boolean(), nullable=True))
    op.add_column('goals', sa.Column('frozen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'frozen_at')
    op.drop_column('goals', 'frozen')
    # ### end Alembic commands ###
