"""schema_improvements_v1

Revision ID: d9137345cd3a
Revises: 2402e697b10b
Create Date: 2026-02-20 01:52:52.378637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9137345cd3a'
down_revision: Union[str, Sequence[str], None] = '2402e697b10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_levels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('time_scope', sa.String(), nullable=True),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('default_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_goals',
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'goal_id')
    )
    op.create_table('program_block_goals',
    sa.Column('program_block_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_block_id'], ['program_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_block_id', 'goal_id')
    )
    op.create_table('program_day_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_day_id', sa.String(), nullable=False),
    sa.Column('session_template_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_template_id'], ['session_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_day_sessions_program_day_id'), 'program_day_sessions', ['program_day_id'], unique=False)
    op.create_index(op.f('ix_program_day_sessions_session_id'), 'program_day_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_program_day_sessions_session_template_id'), 'program_day_sessions', ['session_template_id'], unique=False)
    op.create_table('target_metric_conditions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('metric_definition_id', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_metric_conditions_target_id'), 'target_metric_conditions', ['target_id'], unique=False)
    op.create_table('target_contribution_ledgers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('activity_instance_id', sa.String(), nullable=False),
    sa.Column('metric_condition_id', sa.String(), nullable=False),
    sa.Column('contributed_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_instance_id'], ['activity_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_condition_id'], ['target_metric_conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_contribution_ledgers_activity_instance_id'), 'target_contribution_ledgers', ['activity_instance_id'], unique=False)
    op.create_index(op.f('ix_target_contribution_ledgers_target_id'), 'target_contribution_ledgers', ['target_id'], unique=False)
    op.add_column('activity_goal_associations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_activity_instances_root_deleted_session'), table_name='activity_instances')
    op.drop_column('activity_instances', 'practice_session_id')
    op.drop_index(op.f('ix_event_logs_root_timestamp'), table_name='event_logs')
    op.add_column('goal_activity_group_associations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('level_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_goals_root_deleted_completed'), table_name='goals')
    op.drop_index(op.f('ix_goals_root_deleted_type'), table_name='goals')
    op.create_index(op.f('ix_goals_level_id'), 'goals', ['level_id'], unique=False)
    op.create_index('ix_goals_root_deleted_level', 'goals', ['root_id', 'deleted_at', 'level_id'], unique=False)
    op.create_foreign_key(None, 'goals', 'goal_levels', ['level_id'], ['id'])
    op.drop_column('goals', 'type')
    op.drop_index(op.f('ix_metric_values_root_id'), table_name='metric_values')
    op.drop_constraint(op.f('metric_values_root_id_fkey'), 'metric_values', type_='foreignkey')
    op.drop_column('metric_values', 'root_id')
    op.create_index(op.f('ix_notes_nano_goal_id'), 'notes', ['nano_goal_id'], unique=False)
    op.drop_column('program_blocks', 'goal_ids')
    op.add_column('program_day_goals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('programs', 'goal_ids')
    op.add_column('session_goals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('session_goals', 'association_source',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('session_template_goals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_sessions_root_deleted_created'), table_name='sessions')
    op.add_column('targets', sa.Column('template_id', sa.String(), nullable=True))
    op.add_column('targets', sa.Column('activity_group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_targets_activity_group_id'), 'targets', ['activity_group_id'], unique=False)
    op.create_foreign_key(None, 'targets', 'target_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'targets', 'activity_groups', ['activity_group_id'], ['id'], ondelete='SET NULL')
    op.drop_column('targets', 'metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.drop_index(op.f('ix_targets_activity_group_id'), table_name='targets')
    op.drop_column('targets', 'activity_group_id')
    op.drop_column('targets', 'template_id')
    op.create_index(op.f('ix_sessions_root_deleted_created'), 'sessions', ['root_id', 'deleted_at', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('session_template_goals', 'deleted_at')
    op.alter_column('session_goals', 'association_source',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'manual'::character varying"),
               existing_nullable=False)
    op.drop_column('session_goals', 'deleted_at')
    op.add_column('programs', sa.Column('goal_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('program_day_goals', 'deleted_at')
    op.add_column('program_blocks', sa.Column('goal_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notes_nano_goal_id'), table_name='notes')
    op.add_column('metric_values', sa.Column('root_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('metric_values_root_id_fkey'), 'metric_values', 'goals', ['root_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_metric_values_root_id'), 'metric_values', ['root_id'], unique=False)
    op.add_column('goals', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_index('ix_goals_root_deleted_level', table_name='goals')
    op.drop_index(op.f('ix_goals_level_id'), table_name='goals')
    op.create_index(op.f('ix_goals_root_deleted_type'), 'goals', ['root_id', 'deleted_at', 'type'], unique=False)
    op.create_index(op.f('ix_goals_root_deleted_completed'), 'goals', ['root_id', 'deleted_at', 'completed'], unique=False)
    op.drop_column('goals', 'level_id')
    op.drop_column('goal_activity_group_associations', 'deleted_at')
    op.create_index(op.f('ix_event_logs_root_timestamp'), 'event_logs', ['root_id', sa.literal_column('timestamp DESC')], unique=False)
    op.add_column('activity_instances', sa.Column('practice_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_activity_instances_root_deleted_session'), 'activity_instances', ['root_id', 'deleted_at', 'session_id'], unique=False)
    op.drop_column('activity_goal_associations', 'deleted_at')
    op.drop_index(op.f('ix_target_contribution_ledgers_target_id'), table_name='target_contribution_ledgers')
    op.drop_index(op.f('ix_target_contribution_ledgers_activity_instance_id'), table_name='target_contribution_ledgers')
    op.drop_table('target_contribution_ledgers')
    op.drop_index(op.f('ix_target_metric_conditions_target_id'), table_name='target_metric_conditions')
    op.drop_table('target_metric_conditions')
    op.drop_index(op.f('ix_program_day_sessions_session_template_id'), table_name='program_day_sessions')
    op.drop_index(op.f('ix_program_day_sessions_session_id'), table_name='program_day_sessions')
    op.drop_index(op.f('ix_program_day_sessions_program_day_id'), table_name='program_day_sessions')
    op.drop_table('program_day_sessions')
    op.drop_table('program_block_goals')
    op.drop_table('program_goals')
    op.drop_table('target_templates')
    op.drop_table('goal_levels')
    # ### end Alembic commands ###
