"""Add event_logs table

Revision ID: e51e92965cf8
Revises: d09aa8e14566
Create Date: 2026-01-22 22:39:07.264498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e51e92965cf8'
down_revision: Union[str, Sequence[str], None] = 'd09aa8e14566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('root_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_root_id'), 'event_logs', ['root_id'], unique=False)
    op.drop_index(op.f('ix_activity_definitions_group_id'), table_name='activity_definitions')
    op.drop_index(op.f('ix_activity_instances_activity_def_id'), table_name='activity_instances')
    op.drop_index(op.f('ix_activity_instances_deleted_at'), table_name='activity_instances')
    op.alter_column('goals', 'allow_manual_completion',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('goals', 'track_activities',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_goals_deleted_at'), table_name='goals')
    op.drop_index(op.f('ix_goals_parent_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_root_type'), table_name='goals')
    op.drop_index(op.f('ix_goals_type'), table_name='goals')
    op.drop_index(op.f('ix_programs_is_active'), table_name='programs')
    op.drop_index(op.f('ix_sessions_completed'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_deleted_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_root_deleted'), table_name='sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_root_deleted'), 'sessions', ['root_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_sessions_deleted_at'), 'sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_completed'), 'sessions', ['completed'], unique=False)
    op.create_index(op.f('ix_programs_is_active'), 'programs', ['is_active'], unique=False)
    op.create_index(op.f('ix_goals_type'), 'goals', ['type'], unique=False)
    op.create_index(op.f('ix_goals_root_type'), 'goals', ['root_id', 'type'], unique=False)
    op.create_index(op.f('ix_goals_parent_id'), 'goals', ['parent_id'], unique=False)
    op.create_index(op.f('ix_goals_deleted_at'), 'goals', ['deleted_at'], unique=False)
    op.alter_column('goals', 'track_activities',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('goals', 'allow_manual_completion',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.create_index(op.f('ix_activity_instances_deleted_at'), 'activity_instances', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_instances_activity_def_id'), 'activity_instances', ['activity_definition_id'], unique=False)
    op.create_index(op.f('ix_activity_definitions_group_id'), 'activity_definitions', ['group_id'], unique=False)
    op.drop_index(op.f('ix_event_logs_root_id'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
