"""add day_of_week to program_days

Revision ID: ed5d85f26358
Revises: 9b326a14881c
Create Date: 2026-01-26 16:18:43.393904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5d85f26358'
down_revision: Union[str, Sequence[str], None] = '9b326a14881c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_days', sa.Column('day_of_week', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_days', 'day_of_week')
    # ### end Alembic commands ###
