"""check_sync

Revision ID: f55ae9e336e0
Revises: 94a9feab5041
Create Date: 2026-02-02 15:36:35.732914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55ae9e336e0'
down_revision: Union[str, Sequence[str], None] = '94a9feab5041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if parent_id already exists (it might if manual script was run locally)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('activity_groups')]
    
    if 'parent_id' not in columns:
        op.add_column('activity_groups', sa.Column('parent_id', sa.String(), nullable=True))
        op.create_foreign_key('fk_activity_groups_parent', 'activity_groups', 'activity_groups', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_groups_parent_id'), 'activity_groups', ['parent_id'], unique=False)
    op.create_index(op.f('ix_metric_values_activity_instance_id'), 'metric_values', ['activity_instance_id'], unique=False)
    op.create_index(op.f('ix_sessions_program_day_id'), 'sessions', ['program_day_id'], unique=False)
    op.create_index(op.f('ix_sessions_template_id'), 'sessions', ['template_id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_template_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_program_day_id'), table_name='sessions')
    op.drop_index(op.f('ix_metric_values_activity_instance_id'), table_name='metric_values')
    op.drop_index(op.f('ix_activity_groups_parent_id'), table_name='activity_groups')
    # ### end Alembic commands ###
    op.drop_constraint('fk_activity_groups_parent', 'activity_groups', type_='foreignkey')
    op.drop_column('activity_groups', 'parent_id')

