"""add activity_instance_id to targets

Revision ID: ff40dedbdfeb
Revises: d0e371b35146
Create Date: 2026-03-05 17:24:41.185585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff40dedbdfeb'
down_revision: Union[str, Sequence[str], None] = 'd0e371b35146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('activity_instance_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_targets_activity_instance_id'), 'targets', ['activity_instance_id'], unique=False)
    op.create_foreign_key(None, 'targets', 'activity_instances', ['activity_instance_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.drop_index(op.f('ix_targets_activity_instance_id'), table_name='targets')
    op.drop_column('targets', 'activity_instance_id')
    # ### end Alembic commands ###
