import {
    ActivityGroupMixVisualizationChart,
    ActivityLineGraphChart,
    ActivityMetricVolumeVisualizationChart,
    ActivityPersonalBestChart,
    ActivityScatterPlotChart,
    ActivityTimeByActivityChart,
    ActivityTotalsVisualizationChart,
    GoalAgingVisualizationChart,
    GoalCompletionRateByLevelChart,
    GoalCompletionTimelineChart,
    GoalDetailChart,
    GoalMomentumVisualizationChart,
    GoalSummaryChart,
    GoalTimeDistributionChart,
    SessionCompletionRateVisualizationChart,
    SessionConsistencyVisualizationChart,
    SessionDurationHistogramChart,
    SessionDurationTrendChart,
    SessionHeatmapChart,
    SessionPlannedVsActualVisualizationChart,
    SessionSectionPieChart,
    SessionStartDistributionChart,
    SessionStreaksChart,
    SessionSummaryChart,
    SessionWeeklyChart,
    StaleGoalsVisualizationChart,
} from './VisualizationCharts';
import {
    ActivityMetricControls,
    ActivityTotalsVisualizationControls,
    EmptyControls,
    GoalDetailControls,
    GoalTimeDistributionControls,
    HeatmapControls,
} from './VisualizationControls';

export const VISUALIZATION_CATEGORIES = [
    { id: 'goals', name: 'Goals', iconType: 'category:goals' },
    { id: 'sessions', name: 'Sessions', iconType: 'category:sessions' },
    { id: 'activities', name: 'Activities', iconType: 'category:activities' },
];

export const VISUALIZATION_REGISTRY = [
    {
        id: 'stats',
        category: 'goals',
        name: 'Summary Stats',
        iconType: 'goals:stats',
        defaultState: {},
        selectionRequirements: {},
        Chart: GoalSummaryChart,
        Controls: EmptyControls,
    },
    {
        id: 'completionTimeline',
        category: 'goals',
        name: 'Completion Timeline',
        iconType: 'goals:completionTimeline',
        defaultState: {},
        selectionRequirements: {},
        Chart: GoalCompletionTimelineChart,
        Controls: EmptyControls,
    },
    {
        id: 'timeDistribution',
        category: 'goals',
        name: 'Time Spent Per Goal',
        iconType: 'goals:timeDistribution',
        defaultState: { durationMode: 'activity', inheritanceMode: 'direct' },
        selectionRequirements: {},
        Chart: GoalTimeDistributionChart,
        Controls: GoalTimeDistributionControls,
    },
    {
        id: 'completionRateByLevel',
        category: 'goals',
        name: 'Completion Rate',
        iconType: 'goals:completionRateByLevel',
        defaultState: {},
        selectionRequirements: {},
        Chart: GoalCompletionRateByLevelChart,
        Controls: EmptyControls,
    },
    {
        id: 'goalAging',
        category: 'goals',
        name: 'Goal Aging',
        iconType: 'goals:goalAging',
        defaultState: {},
        selectionRequirements: {},
        Chart: GoalAgingVisualizationChart,
        Controls: EmptyControls,
    },
    {
        id: 'goalMomentum',
        category: 'goals',
        name: 'Goal Momentum',
        iconType: 'goals:goalMomentum',
        defaultState: {},
        selectionRequirements: {},
        Chart: GoalMomentumVisualizationChart,
        Controls: EmptyControls,
    },
    {
        id: 'staleGoals',
        category: 'goals',
        name: 'Stale Goals',
        iconType: 'goals:staleGoals',
        defaultState: {},
        selectionRequirements: {},
        Chart: StaleGoalsVisualizationChart,
        Controls: EmptyControls,
    },
    {
        id: 'goalDetail',
        category: 'goals',
        name: 'Goal Detail View',
        iconType: 'goals:goalDetail',
        defaultState: { chart: 'duration' },
        selectionRequirements: { goal: true },
        Chart: GoalDetailChart,
        Controls: GoalDetailControls,
    },
    {
        id: 'stats',
        category: 'sessions',
        name: 'Summary Stats',
        iconType: 'sessions:stats',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionSummaryChart,
        Controls: EmptyControls,
    },
    {
        id: 'durationTrend',
        category: 'sessions',
        name: 'Duration Trend',
        iconType: 'sessions:durationTrend',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionDurationTrendChart,
        Controls: EmptyControls,
    },
    {
        id: 'sectionPie',
        category: 'sessions',
        name: 'Section Time',
        iconType: 'sessions:sectionPie',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionSectionPieChart,
        Controls: EmptyControls,
    },
    {
        id: 'heatmap',
        category: 'sessions',
        name: 'Activity Heatmap',
        iconType: 'sessions:heatmap',
        defaultState: { months: 12 },
        selectionRequirements: {},
        Chart: SessionHeatmapChart,
        Controls: HeatmapControls,
    },
    {
        id: 'streaks',
        category: 'sessions',
        name: 'Streak Timeline',
        iconType: 'sessions:streaks',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionStreaksChart,
        Controls: EmptyControls,
    },
    {
        id: 'weeklyChart',
        category: 'sessions',
        name: 'Weekly Chart',
        iconType: 'sessions:weeklyChart',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionWeeklyChart,
        Controls: EmptyControls,
    },
    {
        id: 'completionRate',
        category: 'sessions',
        name: 'Completion Rate',
        iconType: 'sessions:completionRate',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionCompletionRateVisualizationChart,
        Controls: EmptyControls,
    },
    {
        id: 'startDistribution',
        category: 'sessions',
        name: 'Start Times',
        iconType: 'sessions:startDistribution',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionStartDistributionChart,
        Controls: EmptyControls,
    },
    {
        id: 'durationHistogram',
        category: 'sessions',
        name: 'Duration Histogram',
        iconType: 'sessions:durationHistogram',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionDurationHistogramChart,
        Controls: EmptyControls,
    },
    {
        id: 'plannedVsActual',
        category: 'sessions',
        name: 'Planned vs Actual',
        iconType: 'sessions:plannedVsActual',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionPlannedVsActualVisualizationChart,
        Controls: EmptyControls,
    },
    {
        id: 'consistency',
        category: 'sessions',
        name: 'Consistency',
        iconType: 'sessions:consistency',
        defaultState: {},
        selectionRequirements: {},
        Chart: SessionConsistencyVisualizationChart,
        Controls: EmptyControls,
    },
    {
        id: 'scatterPlot',
        category: 'activities',
        name: 'Scatter Plot',
        iconType: 'activities:scatterPlot',
        defaultState: { setsHandling: 'top', selectedSplit: 'all', metricX: null, metricY: null },
        selectionRequirements: { activity: true },
        Chart: ActivityScatterPlotChart,
        Controls: ActivityMetricControls,
    },
    {
        id: 'lineGraph',
        category: 'activities',
        name: 'Line Graph',
        iconType: 'activities:lineGraph',
        defaultState: { setsHandling: 'top', selectedSplit: 'all', metric: null, metricY2: null },
        selectionRequirements: { activity: true },
        Chart: ActivityLineGraphChart,
        Controls: ActivityMetricControls,
    },
    {
        id: 'activityFrequency',
        category: 'activities',
        name: 'Activity Totals',
        iconType: 'activities:activityFrequency',
        defaultState: { metric: 'instances', showGroups: false, limit: 15 },
        selectionRequirements: {},
        Chart: ActivityTotalsVisualizationChart,
        Controls: ActivityTotalsVisualizationControls,
    },
    {
        id: 'timeByActivity',
        category: 'activities',
        name: 'Time Per Activity',
        iconType: 'activities:timeByActivity',
        defaultState: {},
        selectionRequirements: {},
        Chart: ActivityTimeByActivityChart,
        Controls: EmptyControls,
    },
    {
        id: 'personalBest',
        category: 'activities',
        name: 'Personal Best',
        iconType: 'activities:personalBest',
        defaultState: {},
        selectionRequirements: { activity: true },
        Chart: ActivityPersonalBestChart,
        Controls: ActivityMetricControls,
    },
    {
        id: 'metricVolume',
        category: 'activities',
        name: 'Metric Volume',
        iconType: 'activities:metricVolume',
        defaultState: {},
        selectionRequirements: { activity: true },
        Chart: ActivityMetricVolumeVisualizationChart,
        Controls: ActivityMetricControls,
    },
    {
        id: 'groupMix',
        category: 'activities',
        name: 'Group Mix',
        iconType: 'activities:groupMix',
        defaultState: {},
        selectionRequirements: {},
        Chart: ActivityGroupMixVisualizationChart,
        Controls: EmptyControls,
    },
];

export function getVisualizationsByCategory(category) {
    return VISUALIZATION_REGISTRY.filter((visualization) => visualization.category === category);
}

export function getVisualization(category, id) {
    return VISUALIZATION_REGISTRY.find((visualization) => (
        visualization.category === category && visualization.id === id
    )) || null;
}

export function getVisualizationKey(category, id) {
    return category && id ? `${category}:${id}` : null;
}

export function getVisualizationDefaultState(category, id) {
    const visualization = getVisualization(category, id);
    return visualization ? { ...visualization.defaultState } : {};
}
